[package]
name = "reflector-rs"
version = "0.1.0"
authors = ["Daniel Buch Hansen <boogiewasthere@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "^1.3.0", features = ["attributes"] }
serde_json = "^1.0.44"
surf = "^1.0.3"
serde = { version = "^1.0.103", features = ["derive"] }
chrono = { version = "^0.4.10", features = ["serde"] }
url = "^2.1.0"
itertools = "^0.8.2"
structopt = "0.3.5"
anyhow = "1.0.25"
env_logger = "0.7.1"
