[package]
name = "Speculum"
version = "0.1.0"
authors = ["Daniel Buch Hansen <boogiewasthere@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "^0.2.6", features = ["full"] }
serde_json = "^1.0.44"
serde = { version = "^1.0.103", features = ["derive"] }
chrono = { version = "^0.4.10", features = ["serde"] }
url = "^2.1.0"
itertools = "^0.8.2"
structopt = "0.3.5"
env_logger = "0.7.1"
hyper = "0.13.1"
hyper-tls = "0.4.0"
bytes = "0.5.3"
users = "0.9.1"
